name: MSBuild with Windows 10 SDK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # Ensures submodules are fetched

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install v143 toolset
        run: |
          choco install visualstudio2017buildtools --params "--add Microsoft.VisualStudio.Component.VC.v143"

      - name: Build with Windows 10 SDK
        run: msbuild MWFixes.sln /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v143

      - name: Copy MWFixes.ini to OutDir
        run: |
          if (!(Test-Path -Path "bin\Release\scripts")) {
              mkdir "bin\Release\scripts"
              Write-Host "Directory created: bin\Release\scripts"
          } else {
              Write-Host "Directory already exists: bin\Release\scripts"
          }

          if (Test-Path -Path "MWFixes.ini") {
              copy "MWFixes.ini" "bin\Release\scripts\MWFixes.ini"
              Write-Host "Copied MWFixes.ini to bin\Release\scripts"
          } else {
              Write-Host "MWFixes.ini not found. Copy failed."
              exit 1
          }
        shell: pwsh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MWFixes-artifacts
          path: |
            bin\Release\scripts\*

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            bin\Release\scripts\*
            MWFixes.ini
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
