name: MSBuild with Windows 10 SDK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install v143 toolset
        run: |
          choco install visualstudio2017buildtools --params "--add Microsoft.VisualStudio.Component.VC.v143"

      - name: Build with Windows 10 SDK
        run: msbuild MWFixes.sln /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v143

      - name: Prepare scripts folder
        run: |
          mkdir -Force bin\Release\scripts
          copy "bin\Release\MWFixes.asi" "bin\Release\scripts\MWFixes.asi"
          copy "MWFixes.ini" "bin\Release\scripts\MWFixes.ini"
        shell: pwsh

      - name: Create ZIP with scripts folder
        run: |
          Compress-Archive -Path bin\Release\scripts\* -DestinationPath MWFixes.zip
        shell: pwsh

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MWFixes-Release
          path: MWFixes.zip

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: MWFixes.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
